travis:
  secure:
    BINSTAR_TOKEN: dYH0XL7Lm2IDKn9DRvtB1VIRipz7xrANoyE5NIyKShFoUcAaDkIMf8W26m5/SHgxl4vnf/3YzeifNucPl6oU3Btjefz4h1GoeWqXOmnyBh9yMa2to6xEI7zm05Nbdtac54/SNpTDhpeuIUhbR4jogym8xoTzZXImtFV2feVy8XTR3TOtQEX1He3NNU2LEevjzCGI2QRnVuK/iUP6MA+Rrkz7JS27LfqLRcodtyjq7ajuatPLRf5pYJg2y74FnYf/VUnYYbgGqbMKFQpvzy4g41/IgOtlEb72+aJjsREOoFuhMf7WGCFci5ynlu/oQ42XWACdHEIkJwtCkqhgnL9MUxoAowOFkuJTLZP4ucQ9MXmWC4lXvL1mlDZJ1w/LSpjnOuH797f8GFTitQXehE/VTtOwNFlOp2NI3uocxPT6uaztg0lNVHso0moYbsnfs3sup4Usi7UKPbzZ0LEcbVKmVYxTbbKfTUUkYNczWGnZOInYOg5+zbLwRfEEXCoy+AmkoFu1A+fjmbGQ6iEXw5U+zZ0j+6q+LsIv2+6XHMafg5KsFmBgzcO1WeztRjHBMfrCzqF6sLGW1BUaMhw5eahxYRwBeG3gMi/2vvThhGIHmlVAO76AreGGVgIZdeHAacZKaMCq+gtBWdcdFw4RkDTEIOetIvj/2LihMgp341bM6Y8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
